# Generated by Django 3.2.9 on 2021-12-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentModel',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='grade',
            new_name='grades',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student',
            new_name='name',
        ),
    ]
